"""Add string lengths to ledger entry table

Revision ID: 51f1096b2a52
Revises: 1a907125bfad
Create Date: 2025-02-26 01:33:57.676620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f1096b2a52'
down_revision: Union[str, None] = '1a907125bfad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
