"""Create ledger entry table with string lengths

Revision ID: 160f6e089aad
Revises: 26268f7687bc
Create Date: 2025-02-26 01:33:20.818888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "160f6e089aad"
down_revision: Union[str, None] = "26268f7687bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
